external-api:
  url: "http://bmw.external.com"
quarkus:
  http:
    port: 8081
    cors:
      ~: true
      origins: /.*/
      headers:
        - accept
        - authorization
        - content-type
      methods:
        - GET
        - POST
        - PUT
        - DELETE
  datasource:
    db-kind: postgresql
    devservices:
      enabled: true
      reuse: false
      image-name: "postgres:14.10-alpine"
      container-env:
        "POSTGRES_DB": "fs_academy"
        "POSTGRES_USER": "postgres"
        "POSTGRES_PASSWORD": "postgres"
      port: 5433
      volumes:
        "db/init-db": "/docker-entrypoint-initdb.d"
      db-name: "fs_academy"
      username: "postgres"
      password: "postgres"
    jdbc:
      url: jdbc:postgresql://localhost:5433/fs_academy
      initial-size: 2
      min-size: 2
      max-size: 5
  liquibase:
    migrate-at-start: true
    drop-first: true
    search-paths:
      - "db"
    change-log: "db/changelog.xml"
  hibernate-orm:
    packages: com.ctw.workstation
    validate-in-dev-mode: false
    database:
      generation: none
    log:
      sql: ${hibernate_orm_log_sql:false}
  log:
    min-level: DEBUG
    level: INFO
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] %s%e%n %X{request.id} %X{request.path}"
      json: false
  rest-client:
    external-api:
      url:
        ${external-api.url}


