name: ci
description: "Login and push to Docker hub"
inputs:
  dockerhub-username:
    description: "docker username"
  dockerhub-token:
    description: "docker password"

runs:
  using: composite
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-token }}

