name: ci
description: "Login and push to Docker hub"

inputs:
  dockerhub_username:
    description: "docker username"
  dockerhub_token:
    description: "docker password"

on:
  push:
    branches: main

jobs:
  runs-on: ubuntu-latest
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-token }}
    - name: Push image to Docker Hub
      run: docker push anarodrigues141/${{env.DOCKER_IMAGE_NAME}}
      shell: bash
