name: ci

inputs:
  dockerhub-username:
    description: "docker username"
  dockerhub-token:
    description: "docker password"

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.dockerhub-username }}
          password: ${{ inputs.dockerhub-token }}
